"Resource/UI/LoadoutPresetPanel.res"
{
"loadout_preset_panel"
{
"ControlName""CLoadoutPresetPanel"
"fieldName""loadout_preset_panel"

"presetbutton_kv"
{
"zpos""20"
"wide""30"
"tall""6"
"visible""0"
"enabled""1"
"font""Nada"
"textAlignment""center"
"textinsetx""1"
"dulltext""1"
"brighttext""1"
"Command"""
"sound_depressed""UI/buttonclick.wav"
"sound_released""UI/buttonclickrelease.wav"
"centerwrap""1"
"paintbackground""1"
}
}
}
